namespace Bidzy.Domain.Enum
{
    public enum NotificationType
    {
        AUCTIONSTART, AUCTIONEND, AUCTIONCANCELLED, PLACEBID, WINBID, NEWBID, USER, SYSTEM, PAYMENTFAILED, PAYMENTREFUNDED
    }
}
