version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=db;Database=BidzyDb;User=sa;Password=YourStrong!Passw0rd;"
      ConnectionStrings__HangfireConnection: "Server=db;Database=BidzyDb;User=sa;Password=YourStrong!Passw0rd;"
      EmailSettings__Sender: "bidzyweb@gmail.com"
      EmailSettings__AppPassword: "ecwn poeh vovr unpd"
      Jwt__Key: "bidzyUltraSecureKey_2025!@#LongEnoughToPass"
      Jwt__Issuer: "Bidzy"
      Jwt__Audience: "BidzyUsers"
      Stripe__PublishableKey: "pk_test_51RrLPcKB1cfct2lQWheAgnRqb01YuD2lKqf2wYM0ha3TKOICZoLHWaSTS0GFFI4irWQ1COFlIw0TCl7GpO7xTmbC00GOYavsQN"
      Stripe__SecretKey: "sk_test_51RrLPcKB1cfct2lQfbfGI4T0UubYMMmhlHSVLWClBRqiUEosPkVv6QUjCPll1i7mR05BwUOm5Vk808cXuaMx4k6E00WsUxEQ4j"
      Stripe__WebhookSecret: "whsec_515f4f06b0628ea7bcbe2376aa5c3f1974547bb6ea9407c946104b610a96a864."
      Stripe__Currency: "usd"
      Stripe__CommissionRate: "0.10"
      IpRateLimiting__EnableEndpointRateLimiting: "true"
      IpRateLimiting__StackBlockedRequests: "false"
      IpRateLimiting__RealIpHeader: "X-Real-IP"
      IpRateLimiting__ClientIdHeader: "X-ClientId"
      IpRateLimiting__HttpStatusCode: "429"
  db:
    image: mcr.microsoft.com/mssql/server:2022-lts
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/lib/mssql

volumes:
  db-data: